name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate
  any sound from any source (asset/file/URL/stream) in a variety of audio
  formats with gapless playback.
version: 0.9.42
repository: https://github.com/ryanheise/just_audio/tree/minor/just_audio
issue_tracker: https://github.com/ryanheise/just_audio/issues
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.5.0
  audio_session: ^0.1.21
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  just_audio_platform_interface: ^4.3.0
  just_audio_web: ^0.4.11
  meta: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.0
  rxdart: ">=0.26.0 <0.29.0"
  uuid: ">=3.0.1 <5.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
